[package]
name = "gpui_android"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/gpui_android.rs"

[target.'cfg(target_os = "android")'.dependencies]
gpui.workspace = true
gpui_wgpu.workspace = true
anyhow.workspace = true
collections.workspace = true
futures.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
profiling.workspace = true
smallvec.workspace = true
util.workspace = true
ndk = "0.9"
ndk-context = "0.1"
jni = "0.21"
cosmic-text = "0.14.0"
swash = "0.2.6"
raw-window-handle = "0.6"
